# Generated by Django 5.2 on 2025-04-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('niveau_etudes', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=200)),
                ('concours_souhaite', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DATE_NAISSANCE', 'Extrait de naissance'), ('DIPLOME', 'Diplôme'), ('CERTIFICAT', 'Certificat'), ('MOTIVATION', 'Lettre de motivation'), ('PHOTO', 'Photo')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscriptions.candidat')),
            ],
        ),
    ]
